const RESTAURANTS = [
  {
    id: 'r1',
    name: 'Gerbeaud',
    cuisine: 'Kávézó & Sütemény',
    rating: 4.7,
    priceLevel: 3,
    distance: '0.4 km',
    address: 'Vörösmarty tér 7-8',
    tags: ['Magyar', 'Sütemény', 'Reggeli'],
    emoji: '☕',
    gradient: 'linear-gradient(135deg, #d4a017 0%, #8B5A00 100%)',
  },
  {
    id: 'r2',
    name: 'Onyx Restaurant',
    cuisine: 'Fine Dining',
    rating: 4.9,
    priceLevel: 4,
    distance: '1.1 km',
    address: 'Vörösmarty tér 7',
    tags: ['Fine Dining', 'Magyar', 'Michelin ⭐'],
    emoji: '🌟',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #4a4a6a 100%)',
  },
  {
    id: 'r3',
    name: 'Pizza a Due',
    cuisine: 'Olasz',
    rating: 4.5,
    priceLevel: 2,
    distance: '0.7 km',
    address: 'Váci utca 12',
    tags: ['Pizza', 'Pasta', 'Olasz'],
    emoji: '🍕',
    gradient: 'linear-gradient(135deg, #e63946 0%, #a8201a 100%)',
  },
  {
    id: 'r4',
    name: 'Sushi Sen',
    cuisine: 'Japán',
    rating: 4.6,
    priceLevel: 3,
    distance: '1.5 km',
    address: 'Andrássy út 38',
    tags: ['Sushi', 'Ramen', 'Friss hal'],
    emoji: '🍣',
    gradient: 'linear-gradient(135deg, #2d6a4f 0%, #1b4332 100%)',
  },
  {
    id: 'r5',
    name: 'Blue Tomato',
    cuisine: 'Burger & Grill',
    rating: 4.4,
    priceLevel: 2,
    distance: '0.9 km',
    address: 'Deák Ferenc utca 3',
    tags: ['Burger', 'Grill', 'Craft sör'],
    emoji: '🍔',
    gradient: 'linear-gradient(135deg, #1d3557 0%, #457b9d 100%)',
  },
  {
    id: 'r6',
    name: 'Menza',
    cuisine: 'Magyar Bistro',
    rating: 4.5,
    priceLevel: 2,
    distance: '1.2 km',
    address: 'Liszt Ferenc tér 2',
    tags: ['Magyar', 'Retro', 'Gulyás'],
    emoji: '🥘',
    gradient: 'linear-gradient(135deg, #e9c46a 0%, #f4a261 100%)',
  },
  {
    id: 'r7',
    name: 'Kao Thai',
    cuisine: 'Thai',
    rating: 4.3,
    priceLevel: 2,
    distance: '1.8 km',
    address: 'Paulay Ede utca 14',
    tags: ['Thai', 'Fűszeres', 'Wok'],
    emoji: '🍜',
    gradient: 'linear-gradient(135deg, #ff6b35 0%, #ffd166 100%)',
  },
  {
    id: 'r8',
    name: 'Két Szerecsen',
    cuisine: 'Mediterrán',
    rating: 4.6,
    priceLevel: 2,
    distance: '1.4 km',
    address: 'Nagymező utca 14',
    tags: ['Mediterrán', 'Brunch', 'Bor'],
    emoji: '🥗',
    gradient: 'linear-gradient(135deg, #06d6a0 0%, #1b9aaa 100%)',
  },
  {
    id: 'r9',
    name: 'Falafel Faloda',
    cuisine: 'Közel-keleti',
    rating: 4.2,
    priceLevel: 1,
    distance: '0.6 km',
    address: 'Paulay Ede utca 53',
    tags: ['Falafel', 'Vegetáriánus', 'Olcsó'],
    emoji: '🧆',
    gradient: 'linear-gradient(135deg, #52b788 0%, #2d6a4f 100%)',
  },
  {
    id: 'r10',
    name: 'Rosenstein',
    cuisine: 'Zsidó-Magyar',
    rating: 4.7,
    priceLevel: 3,
    distance: '2.1 km',
    address: 'Mosonyi utca 3',
    tags: ['Hagyományos', 'Magyar', 'Káposzta'],
    emoji: '🍲',
    gradient: 'linear-gradient(135deg, #c77dff 0%, #7b2d8b 100%)',
  },
  {
    id: 'r11',
    name: 'Taco Loco',
    cuisine: 'Mexikói',
    rating: 4.3,
    priceLevel: 2,
    distance: '1.9 km',
    address: 'Király utca 18',
    tags: ['Taco', 'Burrito', 'Margarita'],
    emoji: '🌮',
    gradient: 'linear-gradient(135deg, #fb8500 0%, #ffb703 100%)',
  },
  {
    id: 'r12',
    name: 'Olimpia',
    cuisine: 'Modern Bistro',
    rating: 4.8,
    priceLevel: 3,
    distance: '2.3 km',
    address: 'Alföld utca 6',
    tags: ['Bistro', 'Szezonális', 'Minőségi'],
    emoji: '🍽️',
    gradient: 'linear-gradient(135deg, #3d405b 0%, #81b29a 100%)',
  },
  {
    id: 'r13',
    name: 'Bock Bisztró',
    cuisine: 'Magyar Fine Dining',
    rating: 4.6,
    priceLevel: 3,
    distance: '1.6 km',
    address: 'Erzsébet körút 43-49',
    tags: ['Magyar', 'Bor', 'Foie Gras'],
    emoji: '🍷',
    gradient: 'linear-gradient(135deg, #6b2737 0%, #9b2335 100%)',
  },
  {
    id: 'r14',
    name: 'Padthai Wokbar',
    cuisine: 'Ázsiai',
    rating: 4.4,
    priceLevel: 1,
    distance: '0.8 km',
    address: 'Vámház körút 4',
    tags: ['Wok', 'Pad Thai', 'Gyors'],
    emoji: '🥡',
    gradient: 'linear-gradient(135deg, #ff4d6d 0%, #ff85a1 100%)',
  },
  {
    id: 'r15',
    name: 'Vapiano',
    cuisine: 'Olasz',
    rating: 4.1,
    priceLevel: 2,
    distance: '0.5 km',
    address: 'Bécsi utca 5',
    tags: ['Pasta', 'Pizza', 'Gyors'],
    emoji: '🍝',
    gradient: 'linear-gradient(135deg, #f72585 0%, #7209b7 100%)',
  },
];
